# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JdXSyiJ9y510odaXe_oOhFzSJn8zphDT
"""

#Acomodo de datos 1) ID del producto 2) Nombre del producto 3) Precio del producto por caja (en $MXN)
productos = [[1,"maiz grano",285.55],[2,"pepino",334.72],[3,"tomate verde",129.00]]

costo_envio = 1500

cantidad_a_vender = int(input("Ingrese la cantidad de cajas a vender "))

id_producto = int(input("Ingrese el ID del producto "))

if cantidad_a_vender <= 100:
  if id_producto == productos[0][0]:
    print("El producto es: ",productos[0][1])
    print("El precio por caja es de: ",productos[0][2],"$MXN")

    precio_a_pagar = float((cantidad_a_vender*productos[0][2])+(costo_envio))
    
    print("El precio total a pagar es de:",precio_a_pagar)
    
  if id_producto == productos[1][0]:
    print("El producto es: ",productos[1][1])
    print("El precio por caja es de:",productos[1][2],"$MXN")

    precio_a_pagar = float((cantidad_a_vender*productos[1][2])+(costo_envio))

    print("El precio total a pagar es de:",precio_a_pagar)

  if id_producto == productos[2][0]:
    print("El producto es: ",productos[2][1])
    print("El precio por caja es de:",productos[2][2],"$MXN")

    precio_a_pagar = float((cantidad_a_vender*productos[2][2])+(costo_envio))

    print("El precio total a pagar es de:",precio_a_pagar)
else:
  print("Debido a la cantidad de cajas no se puede realizar la compra")